const PDFDocument = require('pdfkit');
const QRCode = require('qrcode');
const { PrismaClient } = require('@prisma/client');
const analytics = require('./analytics.service');
const aiEval = require('./ai-evaluation.service');
const config = require('../config/env');

const prisma = new PrismaClient();

// ── Helpers ──────────────────────────────────────────────────────────────────

const drawHeader = (doc, title) => {
    doc.rect(0, 0, doc.page.width, 60).fill('#2563eb');
    doc.fillColor('#ffffff').fontSize(20).font('Helvetica-Bold').text('CivicPulse', 40, 18);
    doc.fontSize(10).font('Helvetica').text(title, 40, 40);
    doc.fillColor('#1e293b').moveDown(2);
    doc.y = 80;
};

const drawSectionTitle = (doc, title) => {
    doc.moveDown(0.5);
    doc.fontSize(13).font('Helvetica-Bold').fillColor('#1e293b').text(title);
    doc.moveTo(40, doc.y + 2).lineTo(doc.page.width - 40, doc.y + 2).stroke('#e2e8f0');
    doc.moveDown(0.5);
    doc.font('Helvetica').fontSize(10).fillColor('#334155');
};

const drawKeyValue = (doc, key, value) => {
    doc.font('Helvetica-Bold').text(`${key}: `, { continued: true });
    doc.font('Helvetica').text(String(value));
};

const drawTable = (doc, headers, rows) => {
    const colWidth = (doc.page.width - 80) / headers.length;
    const startX = 40;
    let y = doc.y;

    // Header row
    doc.font('Helvetica-Bold').fontSize(9).fillColor('#64748b');
    headers.forEach((h, i) => doc.text(h, startX + i * colWidth, y, { width: colWidth, align: 'left' }));
    y += 16;
    doc.moveTo(startX, y).lineTo(startX + colWidth * headers.length, y).stroke('#e2e8f0');
    y += 4;

    // Data rows
    doc.font('Helvetica').fontSize(9).fillColor('#334155');
    rows.forEach((row) => {
        if (y > doc.page.height - 60) { doc.addPage(); y = 40; }
        row.forEach((cell, i) => doc.text(String(cell), startX + i * colWidth, y, { width: colWidth, align: 'left' }));
        y += 15;
    });
    doc.y = y + 8;
};

// ── Monthly Report ───────────────────────────────────────────────────────────

const generateMonthlyReport = async () => {
    const doc = new PDFDocument({ size: 'A4', margin: 40 });
    const chunks = [];
    doc.on('data', (chunk) => chunks.push(chunk));

    drawHeader(doc, `Monthly Report — ${new Date().toLocaleDateString('en-US', { month: 'long', year: 'numeric' })}`);

    // Stats
    const stats = await analytics.getDashboardStats('ADMIN', null);
    drawSectionTitle(doc, 'Complaint Overview');
    drawKeyValue(doc, 'Total Complaints', stats.total);
    drawKeyValue(doc, 'Pending', stats.pending);
    drawKeyValue(doc, 'In Progress', stats.inProgress);
    drawKeyValue(doc, 'Resolved', stats.resolved);
    drawKeyValue(doc, 'SLA Breached', stats.breached);

    // Department breakdown
    const depts = await analytics.getByDepartment();
    drawSectionTitle(doc, 'Department Performance');
    drawTable(doc, ['Department', 'Total', 'Resolved', 'Critical'], depts.map((d) => [d.name, d.total, d.resolved, d.critical]));

    // Category distribution
    const cats = await analytics.getByCategory();
    drawSectionTitle(doc, 'Category Distribution');
    drawTable(doc, ['Category', 'Department', 'Count'], cats.slice(0, 15).map((c) => [c.name, c.department, c.count]));

    // Trends
    const trends = await analytics.getTrends();
    drawSectionTitle(doc, 'Weekly Trends (Last 12 Weeks)');
    drawTable(doc, ['Week', 'Submitted', 'Resolved'], trends.map((t) => [t.week, t.submitted, t.resolved]));

    // AI Metrics summary
    try {
        const aiMetrics = await aiEval.getAccuracyMetrics();
        drawSectionTitle(doc, 'AI Model Performance');
        drawKeyValue(doc, 'Mean Absolute Error', aiMetrics.mae);
        drawKeyValue(doc, 'Priority Accuracy', `${aiMetrics.priorityAccuracy}%`);
        drawKeyValue(doc, 'Override Rate', `${aiMetrics.overrideRate}%`);
    } catch (_) {}

    // Footer
    doc.moveDown(2);
    doc.fontSize(8).fillColor('#94a3b8').text(`Generated by CivicPulse on ${new Date().toISOString()}`, 40, doc.page.height - 40, { align: 'center' });

    doc.end();
    return new Promise((resolve) => doc.on('end', () => resolve(Buffer.concat(chunks))));
};

// ── Complaint Receipt ────────────────────────────────────────────────────────

const generateComplaintReceipt = async (complaintId) => {
    const complaint = await prisma.complaint.findUnique({
        where: { id: complaintId },
        include: {
            category: { include: { department: true } },
            citizen: { select: { name: true, email: true } },
            officer: { select: { name: true } },
            logs: { orderBy: { createdAt: 'asc' } },
        },
    });
    if (!complaint) throw new Error('Complaint not found');

    const doc = new PDFDocument({ size: 'A4', margin: 40 });
    const chunks = [];
    doc.on('data', (chunk) => chunks.push(chunk));

    drawHeader(doc, 'Complaint Receipt');

    // QR code
    const trackUrl = `${config.clientUrl}/public/track/${complaintId}`;
    const qrDataUrl = await QRCode.toDataURL(trackUrl, { width: 100, margin: 1 });
    const qrBase64 = qrDataUrl.replace(/^data:image\/png;base64,/, '');
    doc.image(Buffer.from(qrBase64, 'base64'), doc.page.width - 140, 80, { width: 80 });

    // Complaint details
    drawSectionTitle(doc, 'Complaint Details');
    drawKeyValue(doc, 'ID', complaint.id);
    drawKeyValue(doc, 'Title', complaint.title);
    drawKeyValue(doc, 'Status', complaint.status);
    drawKeyValue(doc, 'Priority', complaint.priorityLevel || 'Pending');
    drawKeyValue(doc, 'Category', complaint.category?.name || 'N/A');
    drawKeyValue(doc, 'Department', complaint.category?.department?.name || 'N/A');
    drawKeyValue(doc, 'Citizen', complaint.citizen?.name || 'N/A');
    drawKeyValue(doc, 'Officer', complaint.officer?.name || 'Not assigned');
    drawKeyValue(doc, 'Submitted', new Date(complaint.createdAt).toLocaleString());

    doc.moveDown(0.5);
    doc.font('Helvetica-Bold').text('Description:');
    doc.font('Helvetica').text(complaint.description, { width: doc.page.width - 80 });

    // Timeline
    if (complaint.logs.length > 0) {
        drawSectionTitle(doc, 'Status Timeline');
        drawTable(doc, ['From', 'To', 'Note', 'Date'],
            complaint.logs.map((l) => [l.fromStatus, l.toStatus, l.note || '-', new Date(l.createdAt).toLocaleString()])
        );
    }

    // SLA info
    if (complaint.slaDeadline) {
        drawSectionTitle(doc, 'SLA Information');
        drawKeyValue(doc, 'Deadline', new Date(complaint.slaDeadline).toLocaleString());
        drawKeyValue(doc, 'Breached', complaint.slaBreached ? 'Yes' : 'No');
    }

    // Footer with QR instruction
    doc.moveDown(2);
    doc.fontSize(8).fillColor('#94a3b8').text(`Scan the QR code to track this complaint online. | Generated ${new Date().toISOString()}`, 40, doc.page.height - 40, { align: 'center' });

    doc.end();
    return new Promise((resolve) => doc.on('end', () => resolve(Buffer.concat(chunks))));
};

// ── AI Evaluation Report ─────────────────────────────────────────────────────

const generateAIEvaluationReport = async () => {
    const doc = new PDFDocument({ size: 'A4', margin: 40 });
    const chunks = [];
    doc.on('data', (chunk) => chunks.push(chunk));

    drawHeader(doc, 'AI Model Evaluation Report');

    const metrics = await aiEval.getAllMetrics();

    // Accuracy overview
    drawSectionTitle(doc, 'Accuracy Metrics');
    drawKeyValue(doc, 'Mean Absolute Error (MAE)', metrics.accuracy.mae);
    drawKeyValue(doc, 'Priority Level Accuracy', `${metrics.accuracy.priorityAccuracy}%`);
    drawKeyValue(doc, 'Officer Override Rate', `${metrics.accuracy.overrideRate}%`);
    drawKeyValue(doc, 'Total Scored Complaints', metrics.accuracy.totalScored);
    drawKeyValue(doc, 'Total Officer Feedbacks', metrics.accuracy.totalFeedbacks);

    // Confusion Matrix
    drawSectionTitle(doc, 'Confusion Matrix (Predicted vs Corrected)');
    const levels = ['CRITICAL', 'HIGH', 'MEDIUM', 'LOW'];
    drawTable(doc, ['Predicted \\ Actual', ...levels],
        levels.map((p) => [p, ...levels.map((a) => metrics.accuracy.confusionMatrix[p]?.[a] || 0)])
    );

    // Routing accuracy
    drawSectionTitle(doc, 'Department Routing');
    drawKeyValue(doc, 'Routing Accuracy', `${metrics.routing.accuracy}%`);
    drawKeyValue(doc, 'Correctly Routed', `${metrics.routing.correct} / ${metrics.routing.total}`);

    // Score distribution
    drawSectionTitle(doc, 'Priority Score Distribution');
    drawTable(doc, ['Score Range', 'Count'], metrics.distribution.map((b) => [b.label, b.count]));

    // Sentiment distribution
    drawSectionTitle(doc, 'Sentiment Distribution');
    drawTable(doc, ['Label', 'Count'], metrics.sentiment.map((s) => [s.label, s.count]));

    // Feature importance
    if (metrics.features.length > 0) {
        drawSectionTitle(doc, 'Feature Importance (SHAP)');
        drawTable(doc, ['Feature', 'Importance'], metrics.features.map((f) => [f.feature, f.importance]));
    }

    // Duplicate stats
    drawSectionTitle(doc, 'Duplicate Detection');
    drawKeyValue(doc, 'Total Duplicates Detected', metrics.duplicates.totalDuplicates);
    drawKeyValue(doc, 'Merged', metrics.duplicates.mergedCount);
    drawKeyValue(doc, 'Duplicate Rate', `${metrics.duplicates.duplicateRate}%`);

    doc.moveDown(2);
    doc.fontSize(8).fillColor('#94a3b8').text(`CivicPulse AI Evaluation Report — ${new Date().toISOString()}`, 40, doc.page.height - 40, { align: 'center' });

    doc.end();
    return new Promise((resolve) => doc.on('end', () => resolve(Buffer.concat(chunks))));
};

module.exports = { generateMonthlyReport, generateComplaintReceipt, generateAIEvaluationReport };
